# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 01:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registryServices', '0003_auto_20171121_2157'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistryAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registry_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registryServices.Registry')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
